spring:
  application:
    name: MaskServer
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  web:
    resources:
      static-locations: file:./web/dist/
#  datasource:
#    url: jdbc:mysql://localhost:3306/mask47631?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
#    username: root
#    password: Mask47631
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:sqlite:maskserver.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect

server:
  port: 47631
  ssl:
    enabled: false
    key-store-type: PEM
    key-file: classpath:localhost.key
    certificate-file: classpath:localhost.crt
    client-auth: none

app:
  version: "@project.version@"
  name: "MaskServer"
  description: "MaskServer"
  avatarUrl: ""
  autoGetWeb: true


token:
  secret: MaskSecretKey123456 # 16位密钥，AES-128
  expire-minutes: 4320 # token过期时间，单位分钟

mail:
  host: smtp.qq.com
  port: 465
  username: your@qq.com
  password: your_smtp_auth_code
  from: your@qq.com

file:
  upload-dir: uploads

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
    path: /swagger-ui.html