spring:
  application:
    name: MaskServer
  profiles:
    active: sqlite
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  web:
    resources:
      static-locations: file:./web/

server:
  port: 47631
  ssl:
    enabled: false
    key-store-type: PEM
    key-file: classpath:localhost.key
    certificate-file: classpath:localhost.crt
    client-auth: none

app:
  version: "@project.version@"
  name: "MaskServer"
  description: "MaskServer"
  avatarUrl: ""

token:
  secret: MaskSecretKey123456 # 16位密钥，AES-128
  expire-minutes: 4320 # token过期时间，单位分钟

mail:
  host: smtp.qq.com
  port: 465
  username: your@qq.com
  password: your_smtp_auth_code
  from: your@qq.com

file:
  upload-dir: uploads

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
    path: /swagger-ui.html