name: 打包发布到Releases

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: # 允许手动触发该工作流

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 克隆代码
      uses: actions/checkout@v4
      with:
        ref: main # 指定主分支
        
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: 创建Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files:  |
          ./target/MaskServer.jar
          ./src/main/resources/application.yml
          ./src/main/resources/application-mysql.yml
          ./src/main/resources/application-sqlite.yml
